import {IWaveSystemProduct} from "../../app/shared/models/manufacturer.model";

export const products: IWaveSystemProduct[] = [
  {
    waveSystemProductManufacturer: "surf-lakes",
    waveSystemProductName: "5 waves plunger XL",
    waveSystemProductAbout: "",
    waveSystemProductExcerpt: "",
    waveSystemProductURL: "https://www.youtube.com/zAKwYG1URZE",
    waveSystemProductProductionMethod: "267",
    waveSystemProductLastUpdated: "2019-09-27 15:28:28",
    waveSystemProductKey: "5-waves",
    waveSystemProductTestLocationURL: "",
    waveSystemProductAdditional: ""
  },
  {
    waveSystemProductName: "PerfectSwell",
    waveSystemProductAbout: "",
    waveSystemProductExcerpt: "",
    waveSystemProductManufacturer: "american-wave-machines",
    waveSystemProductURL: "https://perfectswellsurf.com",
    waveSystemProductProductionMethod: "881",
    waveSystemProductLastUpdated: "2019-09-27 15:29:54",
    waveSystemProductKey: "perfect-swell",
    waveSystemProductTestLocationURL: "",
    waveSystemProductAdditional: ""
  },
  {
    waveSystemProductName: "Wavegarden Lagoon",
    waveSystemProductAbout: "",
    waveSystemProductExcerpt: "",
    waveSystemProductManufacturer: "wavegarden",
    waveSystemProductURL: "https://wavegarden.com/wavegarden-cove",
    waveSystemProductProductionMethod: "269",
    waveSystemProductLastUpdated: "2019-09-27 15:31:50",
    waveSystemProductKey: "wavegarden-cove",
    waveSystemProductTestLocationURL: "",
    waveSystemProductAdditional: ""
  },
  {
    waveSystemProductName: "Kelly Slater Wave Co",
    waveSystemProductAbout: "",
    waveSystemProductExcerpt: "",
    waveSystemProductManufacturer: "kelly-slater-wave-compnay",
    waveSystemProductURL: "https://vimeo.com/215697214",
    waveSystemProductProductionMethod: "315",
    waveSystemProductLastUpdated: "2019-09-27 15:33:32",
    waveSystemProductKey: "kelly-slater-wave",
    waveSystemProductTestLocationURL: "",
    waveSystemProductAdditional: ""
  },
  {
    waveSystemProductName: "Unit surf pool 1",
    waveSystemProductAbout: "",
    waveSystemProductExcerpt: "",
    waveSystemProductManufacturer: "unit-parktech-ag",
    waveSystemProductURL: "https://www.surf-pool.com",
    waveSystemProductProductionMethod: "270",
    waveSystemProductLastUpdated: "2019-09-27 15:38:00",
    waveSystemProductKey: "unit-surf-pool-1",
    waveSystemProductTestLocationURL: "",
    waveSystemProductAdditional: ""
  },
  {
    waveSystemProductName: "Unit surf pool 2",
    waveSystemProductAbout: "",
    waveSystemProductExcerpt: "",
    waveSystemProductManufacturer: "unit-parktech-ag",
    waveSystemProductURL: "https://www.surf-pool.com",
    waveSystemProductProductionMethod: "270",
    waveSystemProductLastUpdated: "2019-09-27 15:38:33",
    waveSystemProductKey: "unit-surf-pool-2",
    waveSystemProductTestLocationURL: "",
    waveSystemProductAdditional: ""
  },
  {
    waveSystemProductName: "Citywave",
    waveSystemProductAbout: "",
    waveSystemProductExcerpt: "",
    waveSystemProductManufacturer: "citywave",
    waveSystemProductURL: "https://citywave.de/technology",
    waveSystemProductProductionMethod: "270",
    waveSystemProductLastUpdated: "2019-09-27 15:39:51",
    waveSystemProductKey: "citywave",
    waveSystemProductTestLocationURL: "",
    waveSystemProductAdditional: ""
  },
  {
    waveSystemProductName: "Point Break Surf",
    waveSystemProductAbout: "",
    waveSystemProductExcerpt: "",
    waveSystemProductManufacturer: "murphys-waves-ltd",
    waveSystemProductURL: "https://www.murphyswaves.com/products/surf-pools/point-break-surf",
    waveSystemProductProductionMethod: "271",
    waveSystemProductLastUpdated: "2019-09-27 15:41:33",
    waveSystemProductKey: "point-break-surf",
    waveSystemProductTestLocationURL: "",
    waveSystemProductAdditional: ""
  },
  {
    waveSystemProductName: "SurfPoel",
    waveSystemProductAbout: "",
    waveSystemProductExcerpt: "",
    waveSystemProductManufacturer: "280",
    waveSystemProductURL: "https://surfpoel.nl",
    waveSystemProductProductionMethod: "1004",
    waveSystemProductLastUpdated: "2019-09-27 15:42:55",
    waveSystemProductKey: "surfpoel",
    waveSystemProductTestLocationURL: "",
    waveSystemProductAdditional: ""
  },
  {
    waveSystemProductName: "Okahina Wave",
    waveSystemProductAbout: "",
    waveSystemProductExcerpt: "",
    waveSystemProductManufacturer: "okahina-wave",
    waveSystemProductURL: "https://wavepoolmag.com/how-the-okahina-wave-system-works",
    waveSystemProductProductionMethod: "1041",
    waveSystemProductLastUpdated: "2019-09-27 15:52:40",
    waveSystemProductKey: "okahina-wave",
    waveSystemProductTestLocationURL: "",
    waveSystemProductAdditional: ""
  },
  {
    waveSystemProductName: "Flowrider compact",
    waveSystemProductAbout: "",
    waveSystemProductExcerpt: "",
    waveSystemProductManufacturer: "flowrider-inc",
    waveSystemProductURL: "https://www.flowrider.com/product/flowrider-compact",
    waveSystemProductProductionMethod: "270",
    waveSystemProductLastUpdated: "2019-09-27 15:57:22",
    waveSystemProductKey: "flowrider-compact",
    waveSystemProductTestLocationURL: "",
    waveSystemProductAdditional: ""
  },
  {
    waveSystemProductName: "Flowrider Single",
    waveSystemProductAbout: "",
    waveSystemProductExcerpt: "",
    waveSystemProductManufacturer: "flowrider-inc",
    waveSystemProductURL: "https://www.flowrider.com/product/flowrider-single",
    waveSystemProductProductionMethod: "270",
    waveSystemProductLastUpdated: "2019-09-27 15:58:29",
    waveSystemProductKey: "flowrider-single",
    waveSystemProductTestLocationURL: "",
    waveSystemProductAdditional: ""
  },
  {
    waveSystemProductName: "Flowrider Double",
    waveSystemProductAbout: "",
    waveSystemProductExcerpt: "",
    waveSystemProductManufacturer: "flowrider-inc",
    waveSystemProductURL: "https://www.flowrider.com/product/flowrider-double",
    waveSystemProductProductionMethod: "270",
    waveSystemProductLastUpdated: "2019-09-27 15:59:12",
    waveSystemProductKey: "flowrider-double",
    waveSystemProductTestLocationURL: "",
    waveSystemProductAdditional: ""
  },
  {
    waveSystemProductName: "Flowrider Triple",
    waveSystemProductAbout: "",
    waveSystemProductExcerpt: "",
    waveSystemProductManufacturer: "flowrider-inc",
    waveSystemProductURL: "https://www.flowrider.com/product/flowrider-triple",
    waveSystemProductProductionMethod: "270",
    waveSystemProductLastUpdated: "2019-09-27 15:59:47",
    waveSystemProductKey: "flowrider-triple",
    waveSystemProductTestLocationURL: "",
    waveSystemProductAdditional: ""
  },
  {
    waveSystemProductName: "Flowrider Wave in a Box",
    waveSystemProductAbout: "",
    waveSystemProductExcerpt: "",
    waveSystemProductManufacturer: "flowrider-inc",
    waveSystemProductURL: "https://www.flowrider.com/product/flowrider-wave-in-a-box",
    waveSystemProductProductionMethod: "270",
    waveSystemProductLastUpdated: "2019-09-27 16:00:23",
    waveSystemProductKey: "flowrider-wave-in-a-box",
    waveSystemProductTestLocationURL: "",
    waveSystemProductAdditional: ""
  },
  {
    waveSystemProductName: "Flowrider Mobile",
    waveSystemProductAbout: "",
    waveSystemProductExcerpt: "",
    waveSystemProductManufacturer: "flowrider-inc",
    waveSystemProductURL: "https://www.flowrider.com/product/flowrider-mobile",
    waveSystemProductProductionMethod: "270",
    waveSystemProductLastUpdated: "2019-09-27 16:00:55",
    waveSystemProductKey: "flowrider-mobile",
    waveSystemProductTestLocationURL: "",
    waveSystemProductAdditional: ""
  },
  {
    waveSystemProductName: "Flowbarrel Ten",
    waveSystemProductAbout: "",
    waveSystemProductExcerpt: "",
    waveSystemProductManufacturer: "flowrider-inc",
    waveSystemProductURL: "https://www.flowrider.com/product/flowbarrel-ten",
    waveSystemProductProductionMethod: "270",
    waveSystemProductLastUpdated: "2019-09-27 16:01:42",
    waveSystemProductKey: "flowbarrel-ten",
    waveSystemProductTestLocationURL: "",
    waveSystemProductAdditional: ""
  },
  {
    waveSystemProductName: "Flowbarrel Ten Double",
    waveSystemProductAbout: "",
    waveSystemProductExcerpt: "",
    waveSystemProductManufacturer: "flowrider-inc",
    waveSystemProductURL: "https://www.flowrider.com/product/flowbarrel-ten-double",
    waveSystemProductProductionMethod: "270",
    waveSystemProductLastUpdated: "2019-09-27 16:02:11",
    waveSystemProductKey: "flowbarrel-ten-double",
    waveSystemProductTestLocationURL: "",
    waveSystemProductAdditional: ""
  },
  {
    waveSystemProductName: "WaveOz",
    waveSystemProductAbout: "",
    waveSystemProductExcerpt: "",
    waveSystemProductManufacturer: "flowrider-inc",
    waveSystemProductURL: "https://www.flowrider.com/product/waveoz",
    waveSystemProductProductionMethod: "270",
    waveSystemProductLastUpdated: "2019-09-27 16:03:18",
    waveSystemProductKey: "waveoz",
    waveSystemProductTestLocationURL: "",
    waveSystemProductAdditional: ""
  },
  {
    waveSystemProductName: "LatiTube",
    waveSystemProductAbout: "",
    waveSystemProductExcerpt: "",
    waveSystemProductManufacturer: "flowrider-inc",
    waveSystemProductURL: "https://www.flowrider.com/product/latitube",
    waveSystemProductProductionMethod: "270",
    waveSystemProductLastUpdated: "2019-09-27 16:04:13",
    waveSystemProductKey: "latitube",
    waveSystemProductTestLocationURL: "",
    waveSystemProductAdditional: ""
  },
  {
    waveSystemProductName: "Wavegarden Cove URBNSURF",
    waveSystemProductAbout: "",
    waveSystemProductExcerpt: "",
    waveSystemProductManufacturer: "wavegarden",
    waveSystemProductURL: "https://urbnsurf.com/about",
    waveSystemProductProductionMethod: "881",
    waveSystemProductLastUpdated: "2019-09-27 20:24:19",
    waveSystemProductKey: "wavegarden-urbnsurf",
    waveSystemProductTestLocationURL: "",
    waveSystemProductAdditional: ""
  },
  {
    waveSystemProductName: "Webber Wavepool Australia",
    waveSystemProductAbout: "",
    waveSystemProductExcerpt: "",
    waveSystemProductManufacturer: "webber",
    waveSystemProductURL: "https://wavepoolmag.com/webber-wave-pools-update-us-licenses-and-smart-hulls",
    waveSystemProductProductionMethod: "1004",
    waveSystemProductLastUpdated: "2019-10-03 22:17:26",
    waveSystemProductKey: "wavepool",
    waveSystemProductTestLocationURL: "",
    waveSystemProductAdditional: ""
  },
  {
    waveSystemProductName: "Swellspot",
    waveSystemProductAbout: "",
    waveSystemProductExcerpt: "",
    waveSystemProductManufacturer: "swellspot",
    waveSystemProductURL: "https://www.swellspot.com/index.html",
    waveSystemProductProductionMethod: "391",
    waveSystemProductLastUpdated: "2019-10-04 15:13:42",
    waveSystemProductKey: "swellspot",
    waveSystemProductTestLocationURL: "",
    waveSystemProductAdditional: ""
  },
  {
    waveSystemProductName: "32’ Surfstream",
    waveSystemProductAbout: "",
    waveSystemProductExcerpt: "",
    waveSystemProductManufacturer: "american-wave-machines",
    waveSystemProductURL: "",
    waveSystemProductProductionMethod: "270",
    waveSystemProductLastUpdated: "2019-10-11 19:17:59",
    waveSystemProductKey: "surfstream",
    waveSystemProductTestLocationURL: "",
    waveSystemProductAdditional: ""
  },
  {
    waveSystemProductName: "Surf Wave Pool",
    waveSystemProductAbout: "",
    waveSystemProductExcerpt: "",
    waveSystemProductManufacturer: "whitewaterwest",
    waveSystemProductURL: "https://www.whitewaterwest.com/products/wave-pools",
    waveSystemProductProductionMethod: "391",
    waveSystemProductLastUpdated: "2019-10-13 11:54:21",
    waveSystemProductKey: "surf-wave-pool",
    waveSystemProductTestLocationURL: "",
    waveSystemProductAdditional: ""
  },
  {
    waveSystemProductName: "Freak Peak",
    waveSystemProductAbout: "",
    waveSystemProductExcerpt: "",
    waveSystemProductManufacturer: "american-wave-machines",
    waveSystemProductURL: "https://www.youtube.com/watch?v=TCeNS6tLex4",
    waveSystemProductProductionMethod: "881",
    waveSystemProductLastUpdated: "2019-10-13 12:59:36",
    waveSystemProductKey: "freak-peak",
    waveSystemProductTestLocationURL: "",
    waveSystemProductAdditional: ""
  },
  {
    waveSystemProductName: "Surf Loch, Wave Loch, and Wave House  (>1991) (standing)",
    waveSystemProductAbout: "",
    waveSystemProductExcerpt: "",
    waveSystemProductManufacturer: "surf-loch",
    waveSystemProductURL: "https://www.wavehouse.com/venues",
    waveSystemProductProductionMethod: "270",
    waveSystemProductLastUpdated: "2019-11-02 08:06:51",
    waveSystemProductKey: "wave-house",
    waveSystemProductTestLocationURL: "",
    waveSystemProductAdditional: ""
  },
  {
    waveSystemProductName: "Wave Loch Surfpool (rolling)",
    waveSystemProductAbout: "",
    waveSystemProductExcerpt: "",
    waveSystemProductManufacturer: "surf-loch",
    waveSystemProductURL: "https://www.surfloch.com/technology?gclid=EAIaIQobChMIoeSbmvz36QIVZbR3Ch1CqwckEAAYASABEgL9GfD_BwE",
    waveSystemProductProductionMethod: "881",
    waveSystemProductLastUpdated: "2019-11-02 08:19:45",
    waveSystemProductKey: "wave-loch-surfpool",
    waveSystemProductTestLocationURL: "",
    waveSystemProductAdditional: ""
  },
  {
    waveSystemProductName: "Vapor Wave Product",
    waveSystemProductAbout: "",
    waveSystemProductExcerpt: "",
    waveSystemProductManufacturer: "surf-mountain",
    waveSystemProductURL: "https://swellplanet.mystrikingly.com",
    waveSystemProductProductionMethod: "272",
    waveSystemProductLastUpdated: "2020-04-12 21:14:04",
    waveSystemProductKey: "vapor-wave-product",
    waveSystemProductTestLocationURL: "",
    waveSystemProductAdditional: ""
  },
  {
    waveSystemProductName: "Dexters  BigSurfAZ",
    waveSystemProductAbout: "",
    waveSystemProductExcerpt: "",
    waveSystemProductManufacturer: "phil-dexter",
    waveSystemProductURL: "https://www.inventionandtech.com/category/inventor/phil-dexter",
    waveSystemProductProductionMethod: "271",
    waveSystemProductLastUpdated: "2020-05-10 08:30:30",
    waveSystemProductKey: "dexters-bigsurfaz",
    waveSystemProductTestLocationURL: "",
    waveSystemProductAdditional: ""
  },
  {
    waveSystemProductName: "RESPONSE-ENGINEER carry wave generator",
    waveSystemProductAbout: "",
    waveSystemProductExcerpt: "",
    waveSystemProductManufacturer: "response-engineer-inc",
    waveSystemProductURL: "https://response-engineer.jp/kobe_reyes.html",
    waveSystemProductProductionMethod: "271",
    waveSystemProductLastUpdated: "2020-05-10 20:25:26",
    waveSystemProductKey: "response-engineer-kobe-wave",
    waveSystemProductTestLocationURL: "",
    waveSystemProductAdditional: ""
  },
  {
    waveSystemProductName: "Endless Surf",
    waveSystemProductAbout: "",
    waveSystemProductExcerpt: "",
    waveSystemProductManufacturer: "whitewaterwest",
    waveSystemProductURL: "https://www.surfertoday.com/surfing/la-vague-grand-paris-the-new-wave-pool-by-whitewater",
    waveSystemProductProductionMethod: "881",
    waveSystemProductLastUpdated: "2020-05-22 14:15:10",
    waveSystemProductKey: "endless-surf",
    waveSystemProductTestLocationURL: "",
    waveSystemProductAdditional: ""
  },
  {
    waveSystemProductName: "Plunger 2 - compact plunger pool model",
    waveSystemProductAbout: "",
    waveSystemProductExcerpt: "",
    waveSystemProductManufacturer: "surf-lakes",
    waveSystemProductURL: "https://www.surfertoday.com/surfing/surf-lakes-announce-compact-wave-pool-model",
    waveSystemProductProductionMethod: "267",
    waveSystemProductLastUpdated: "2020-10-03 08:41:24",
    waveSystemProductKey: "plunger-2-compact-plunger-pool-model",
    waveSystemProductTestLocationURL: "",
    waveSystemProductAdditional: ""
  },
  {
    waveSystemProductName: "Wavemaster",
    waveSystemProductAbout: "",
    waveSystemProductExcerpt: "",
    waveSystemProductManufacturer: "olas",
    waveSystemProductURL: "https://www.olassurfingtech.com/index.php",
    waveSystemProductProductionMethod: "272",
    waveSystemProductLastUpdated: "2021-01-10 22:07:20",
    waveSystemProductKey: "wavemaster",
    waveSystemProductTestLocationURL: "",
    waveSystemProductAdditional: ""
  },
  {
    waveSystemProductName: "Webber Wavepool USA",
    waveSystemProductAbout: "",
    waveSystemProductExcerpt: "",
    waveSystemProductManufacturer: "oceansportsdevelopment",
    waveSystemProductURL: "https://oceansportsdevelopment.com/pool",
    waveSystemProductProductionMethod: "1004",
    waveSystemProductLastUpdated: "2021-01-12 21:30:07",
    waveSystemProductKey: "webber-by-osd",
    waveSystemProductTestLocationURL: "",
    waveSystemProductAdditional: ""
  },
  {
    waveSystemProductName: "Blackforestwave",
    waveSystemProductAbout: "",
    waveSystemProductExcerpt: "",
    waveSystemProductManufacturer: "blackforestwave-ev",
    waveSystemProductURL: "https://blackforestwave.de",
    waveSystemProductProductionMethod: "748",
    waveSystemProductLastUpdated: "2021-01-30 21:47:57",
    waveSystemProductKey: "blackforestwave",
    waveSystemProductTestLocationURL: "",
    waveSystemProductAdditional: ""
  },
  {
    waveSystemProductName: "SwelMFG",
    waveSystemProductAbout: "",
    waveSystemProductExcerpt: "",
    waveSystemProductManufacturer: "swellmfg",
    waveSystemProductURL: "https://www.swellmfg.com",
    waveSystemProductProductionMethod: "272",
    waveSystemProductLastUpdated: "2021-04-04 20:35:53",
    waveSystemProductKey: "swelmfg",
    waveSystemProductTestLocationURL: "",
    waveSystemProductAdditional: ""
  },
  {
    waveSystemProductName: "SurfKing wave machine",
    waveSystemProductAbout: "",
    waveSystemProductExcerpt: "",
    waveSystemProductManufacturer: "barrwray",
    waveSystemProductURL: "https://www.barrandwray.com/pools/products-services/wave-machines",
    waveSystemProductProductionMethod: "271",
    waveSystemProductLastUpdated: "2021-08-17 19:56:11",
    waveSystemProductKey: "surfking-wave-machine",
    waveSystemProductTestLocationURL: "",
    waveSystemProductAdditional: ""
  },
  {
    waveSystemProductName: "River",
    waveSystemProductAbout: "",
    waveSystemProductExcerpt: "",
    waveSystemProductManufacturer: "nature",
    waveSystemProductURL: "",
    waveSystemProductProductionMethod: "748",
    waveSystemProductLastUpdated: "2021-08-23 07:07:52",
    waveSystemProductKey: "river",
    waveSystemProductTestLocationURL: "",
    waveSystemProductAdditional: ""
  },
  {
    waveSystemProductName: "Epic Surf (standing)",
    waveSystemProductAbout: "",
    waveSystemProductExcerpt: "",
    waveSystemProductManufacturer: "aquatic-development-group-adg-2",
    waveSystemProductURL: "https://www.epic.surf",
    waveSystemProductProductionMethod: "270",
    waveSystemProductLastUpdated: "2021-08-29 11:20:25",
    waveSystemProductKey: "epic-surf-standing",
    waveSystemProductTestLocationURL: "",
    waveSystemProductAdditional: ""
  },
  {
    waveSystemProductName: "Okahina",
    waveSystemProductAbout: "",
    waveSystemProductExcerpt: "",
    waveSystemProductManufacturer: "okahina-wave",
    waveSystemProductURL: "",
    waveSystemProductProductionMethod: "1041",
    waveSystemProductLastUpdated: "2021-08-31 20:04:22",
    waveSystemProductKey: "okahina",
    waveSystemProductTestLocationURL: "",
    waveSystemProductAdditional: ""
  },
  {
    waveSystemProductName: "Any Wave -CM7",
    waveSystemProductAbout: "",
    waveSystemProductExcerpt: "",
    waveSystemProductManufacturer: "kaana-wave-co-company",
    waveSystemProductURL: "https://kaanawaveco.com/product-2",
    waveSystemProductProductionMethod: "270",
    waveSystemProductLastUpdated: "2021-10-31 16:29:29",
    waveSystemProductKey: "any-wave",
    waveSystemProductTestLocationURL: "",
    waveSystemProductAdditional: ""
  },
  {
    waveSystemProductName: "Dreamwave Modularsystem",
    waveSystemProductAbout: "",
    waveSystemProductExcerpt: "",
    waveSystemProductManufacturer: "dreamwave",
    waveSystemProductURL: "https://www.dreamwave-international.com",
    waveSystemProductProductionMethod: "748",
    waveSystemProductLastUpdated: "2021-12-23 19:18:50",
    waveSystemProductKey: "dreamwave-modularsystem",
    waveSystemProductTestLocationURL: "",
    waveSystemProductAdditional: ""
  },
  {
    waveSystemProductName: "Static Wave Tech France 1",
    waveSystemProductAbout: "",
    waveSystemProductExcerpt: "",
    waveSystemProductManufacturer: "static-wave-technology-france",
    waveSystemProductURL: "https://city-surf-park.com/technologie-vague-indoor",
    waveSystemProductProductionMethod: "270",
    waveSystemProductLastUpdated: "2022-01-21 20:40:48",
    waveSystemProductKey: "static-wave-tech-france-1",
    waveSystemProductTestLocationURL: "",
    waveSystemProductAdditional: ""
  },
  {
    waveSystemProductName: "AllWaves Nr1",
    waveSystemProductAbout: "",
    waveSystemProductExcerpt: "",
    waveSystemProductManufacturer: "allwaves",
    waveSystemProductURL: "https://allwaves.surf/technology",
    waveSystemProductProductionMethod: "1123",
    waveSystemProductLastUpdated: "2022-02-05 20:53:07",
    waveSystemProductKey: "allwaves-nr1",
    waveSystemProductTestLocationURL: "",
    waveSystemProductAdditional: ""
  }
]
